"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Backpack, Check, ChevronRight, CircleAlert, Clock3, ExternalLink, FerrisWheel, MapPin, Mountain, Plane, Route, Ship, Sparkles, TrainFront, Utensils } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Stop = { id: string; time: string; title: string; detail: string; place: string; booked?: boolean; important?: boolean };
type Day = { date: string; short: string; city: string; eyebrow: string; title: string; summary: string; color: string; map: string; stops: Stop[] };
const STORAGE_KEY = "lucas-italia-2026-v4";

const days: Day[] = [
  { date: "Domingo 20 de septiembre", short: "20 SEP", city: "Milán", eyebrow: "Llegada", title: "Aterrizar, cenar ligero y descansar", summary: "La noche es solo logística: al día siguiente toca madrugar para Florencia.", color: "#e4603b", map: "https://www.openstreetmap.org/export/embed.html?bbox=9.17%2C45.46%2C9.23%2C45.51&layer=mapnik", stops: [
    { id: "mxp", time: "19:00", title: "Llegada a Malpensa", detail: "Cuenta con 60–90 minutos para equipaje y salida de la terminal.", place: "MXP", booked: true },
    { id: "express", time: "20:45", title: "Malpensa Express", detail: "Elige Milano Centrale si el hotel está junto a la estación. No reserves el primer tren posible.", place: "MXP → Milano Centrale" },
    { id: "sleep", time: "22:15", title: "Check-in y descanso", detail: "Deja maleta, desayuno y billetes preparados para la mañana.", place: "Milano Centrale" },
  ]},
  { date: "Lunes 21 de septiembre", short: "21 SEP", city: "Florencia", eyebrow: "Primer día", title: "Florencia desde el Duomo hasta el Arno", summary: "Un primer día caminable, sin museos pesados y con el mejor final panorámico.", color: "#ce8b2e", map: "https://www.openstreetmap.org/export/embed.html?bbox=11.22%2C43.75%2C11.29%2C43.79&layer=mapnik", stops: [
    { id: "firenze-train", time: "06:10", title: "Tren de alta velocidad", detail: "Frecciarossa directo a Firenze S.M.N. Llega al andén con al menos 20 minutos de margen.", place: "Milano Centrale → Firenze S.M.N.", booked: true },
    { id: "bagdrop", time: "08:15", title: "Dejar maletas y desayunar", detail: "Confirma con el hotel que admite equipaje antes del check-in.", place: "Santa Maria Novella" },
    { id: "duomo", time: "10:00", title: "Duomo y centro histórico", detail: "Piazza del Duomo, Baptisterio, Via dei Calzaiuoli y Piazza della Signoria.", place: "Centro de Florencia" },
    { id: "market", time: "13:00", title: "Comer en Mercato Centrale", detail: "Opción flexible para probar varias especialidades sin perder la tarde.", place: "San Lorenzo" },
    { id: "oltrarno", time: "16:30", title: "Ponte Vecchio y Oltrarno", detail: "Cruza el río y recorre Santo Spirito antes de subir al mirador.", place: "Oltrarno" },
    { id: "sunset", time: "18:45", title: "Piazzale Michelangelo", detail: "Sube con tiempo; los autobuses 12 y 13 ahorran piernas.", place: "Piazzale Michelangelo" },
  ]},
  { date: "Martes 22 de septiembre", short: "22 SEP", city: "Toscana", eyebrow: "Excursión reservada", title: "Pueblos, viñedos y Pisa", summary: "Día completo ya comprometido: solo falta copiar la hora y punto de encuentro del bono.", color: "#557b5a", map: "https://www.openstreetmap.org/export/embed.html?bbox=10.25%2C42.95%2C11.85%2C44.05&layer=mapnik", stops: [
    { id: "meet", time: "07:15", title: "Punto de encuentro", detail: "Hora orientativa: sustitúyela por la que figure en el bono del tour.", place: "Florencia", booked: true },
    { id: "tour", time: "07:30", title: "Excursión de día completo", detail: "Agua, calzado cómodo y una capa ligera para el final del día.", place: "Toscana", booked: true },
    { id: "tour-return", time: "20:00", title: "Regreso previsto", detail: "Cena sin reserva rígida por si el tráfico retrasa la llegada.", place: "Florencia" },
  ]},
  { date: "Miércoles 23 de septiembre", short: "23 SEP", city: "Florencia", eyebrow: "Arte y barrios", title: "El David primero; la Florencia viva después", summary: "La reserva temprana deja una tarde abierta para elegir un gran museo o pasear sin prisa.", color: "#ce8b2e", map: "https://www.openstreetmap.org/export/embed.html?bbox=11.235%2C43.758%2C11.282%2C43.79&layer=mapnik", stops: [
    { id: "david", time: "08:30", title: "Galería de la Academia", detail: "Entrada para ver el David. Comprueba en el bono el acceso o punto de recogida correcto.", place: "Via Ricasoli 58/60", booked: true },
    { id: "coffee", time: "10:15", title: "Café en Santissima Annunziata", detail: "Pausa tranquila antes de volver a las calles más concurridas.", place: "Piazza SS. Annunziata" },
    { id: "signoria", time: "11:30", title: "Piazza della Signoria", detail: "Palazzo Vecchio, Loggia dei Lanzi y patio de los Uffizi.", place: "Piazza della Signoria" },
    { id: "museum", time: "14:00", title: "Uffizi o Palazzo Pitti", detail: "Elige uno; dos grandes museos en la misma tarde restan más de lo que suman.", place: "Florencia" },
    { id: "last-night", time: "19:00", title: "Última noche en Oltrarno", detail: "Aperitivo, cena toscana y maletas listas antes de dormir.", place: "Santo Spirito" },
  ]},
  { date: "Jueves 24 de septiembre", short: "24 SEP", city: "Como", eyebrow: "Plan reformulado", title: "Llegar al mediodía y vivir Como de verdad", summary: "Sin escala turística en Milán: la tarde se aprovecha junto al lago y termina en Brunate.", color: "#147a89", map: "https://www.openstreetmap.org/export/embed.html?bbox=9.05%2C45.78%2C9.12%2C45.86&layer=mapnik", stops: [
    { id: "florence-como", time: "08:10", title: "Florencia → Como", detail: "Alta velocidad hasta Milano Centrale y regional a Como S. Giovanni. Busca una conexión que llegue entre 11:30 y 12:15.", place: "Firenze S.M.N. → Como S. Giovanni", important: true },
    { id: "como-checkin", time: "12:15", title: "Check-in y comida junto al centro", detail: "Deja el equipaje y come sin sobremesa larga para aprovechar la luz.", place: "Como centro" },
    { id: "old-town", time: "14:00", title: "Duomo y casco histórico", detail: "Duomo, Broletto, San Fedele y callejuelas del centro; todo queda cerca.", place: "Duomo di Como" },
    { id: "promenade", time: "15:45", title: "Paseo del lago hasta Villa Olmo", detail: "Ruta llana y muy visual por el Tempio Voltiano. Si llueve, cambia Villa Olmo por cafés y tiendas del centro.", place: "Lungolago → Villa Olmo" },
    { id: "brunate", time: "18:00", title: "Funicular a Brunate", detail: "Sube antes del atardecer, disfruta las vistas y baja sin apurar el último servicio.", place: "Como–Brunate", important: true },
    { id: "como-dinner", time: "20:15", title: "Cena lombarda", detail: "Busca risotto con pesce persico, polenta o missoltini si te apetece cocina del lago.", place: "Como centro" },
  ]},
  { date: "Viernes 25 de septiembre", short: "25 SEP", city: "Como → MXP", eyebrow: "Día de vuelo", title: "Una mañana corta, bonita y sin carreras", summary: "Bellagio sale del plan. La prioridad es estar en Malpensa hacia las 10:45–11:00 para el vuelo de las 14:00.", color: "#425d73", map: "https://www.openstreetmap.org/export/embed.html?bbox=8.65%2C45.55%2C9.25%2C45.9&layer=mapnik", stops: [
    { id: "lake-breakfast", time: "07:30", title: "Desayuno y último paseo", detail: "Café, cornetto y 30–40 minutos junto al lago. Nada que dependa de un barco.", place: "Piazza Cavour" },
    { id: "checkout", time: "08:30", title: "Check-out", detail: "Billetes, terminal del vuelo y transporte revisados la noche anterior.", place: "Hotel en Como", important: true },
    { id: "airport", time: "08:45", title: "Salida hacia Malpensa", detail: "Plan equilibrado: Como Lago → Saronno y cambio al Malpensa Express. Alternativa cómoda: taxi reservado sobre las 09:00.", place: "Como → MXP", important: true },
    { id: "mxp-arrive", time: "10:30", title: "Llegada objetivo a MXP", detail: "Te deja unas tres horas y media para facturar, seguridad y cualquier imprevisto.", place: "Malpensa Airport" },
    { id: "flight", time: "14:00", title: "Vuelo de regreso", detail: "El plan termina aquí: sin ferris, villas ni conexiones ajustadas esa mañana.", place: "MXP", booked: true, important: true },
  ]},
];

const transfers = [
  { title: "Tren por Saronno", time: "≈ 1 h 25–1 h 45", badge: "Plan equilibrado", detail: "Desde Como Lago hacia Saronno; allí cambia al Malpensa Express. El tramo Saronno–MXP tarda unos 20–25 minutos.", leave: "Salir 08:16–08:46", icon: TrainFront, href: "https://www.trenord.it/en/" },
  { title: "Taxi reservado", time: "≈ 45–70 min", badge: "Más cómodo", detail: "Puerta a puerta y sin cargar maletas en un transbordo. El tráfico manda: no saldría más tarde de las 09:00.", leave: "Reservar 08:45–09:00", icon: Route, href: "https://www.milanomalpensa-airport.com/en/from-to/by-taxi" },
  { title: "Tren vía Milán", time: "≈ 1 h 50–2 h 20", badge: "Solo respaldo", detail: "Es sencillo, pero añade distancia y consume el margen que interesa proteger antes de volar.", leave: "Evitar si hay opción por Saronno", icon: TrainFront, href: "https://www.malpensaexpress.it/en/" },
];
const food = [
  { city: "Florencia", dish: "Schiacciata o lampredotto", when: "Comida rápida", note: "Para el primer día; informal y fácil de encajar entre visitas." },
  { city: "Florencia", dish: "Ribollita, peposo o bistecca", when: "Cena", note: "Mejor en Oltrarno o San Frediano que pegado al Duomo." },
  { city: "Como", dish: "Risotto con pesce persico", when: "Cena del jueves", note: "El plato más reconocible del lago; confirma que el pescado sea local." },
  { city: "Como", dish: "Polenta uncia o missoltini", when: "Alternativa", note: "Cocina lombarda contundente, perfecta si refresca por la noche." },
];
const officialLinks = [
  ["Trenitalia", "https://www.trenitalia.com/en.html"], ["Italo", "https://www.italotreno.com/en"], ["Trenord", "https://www.trenord.it/en/"], ["Malpensa Express", "https://www.malpensaexpress.it/en/"], ["Barcos Lago di Como", "https://www.navigazionelaghi.it/en/tickets-and-timetables-lake-como/"],
];

function HeroIcon({ city }: { city: string }) {
  if (city.includes("Como")) return <Mountain size={18} />;
  if (city === "Toscana") return <Sparkles size={18} />;
  return <MapPin size={18} />;
}

export default function Home() {
  const [activeDay, setActiveDay] = useState(4);
  const [checked, setChecked] = useState<Record<string, boolean>>({});
  const [times, setTimes] = useState<Record<string, string>>({});
  const [saved, setSaved] = useState(false);
  const [flightMode, setFlightMode] = useState<"train" | "taxi">("train");

  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const data = JSON.parse(raw); setChecked(data.checked ?? {}); setTimes(data.times ?? {}); setFlightMode(data.flightMode ?? "train"); } } catch {} }, []);
  const active = days[activeDay];
  const totalStops = days.flatMap((day) => day.stops).length;
  const readyStops = days.flatMap((day) => day.stops).filter((stop) => stop.booked || checked[stop.id]).length;
  const progress = Math.round((readyStops / totalStops) * 100);
  const nextAction = useMemo(() => days.flatMap((day) => day.stops).find((stop) => !stop.booked && !checked[stop.id])?.title ?? "Todo preparado", [checked]);
  function savePlan() { localStorage.setItem(STORAGE_KEY, JSON.stringify({ checked, times, flightMode })); setSaved(true); window.setTimeout(() => setSaved(false), 1800); }

  return <main className="min-h-screen bg-[#f4f1ea] text-[#14211e]">
    <header className="border-b border-black/8 bg-[#f4f1ea]/90 backdrop-blur-xl lg:sticky lg:top-0 lg:z-50"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-3 sm:px-7 lg:px-10">
      <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#123f47] text-white"><Route size={19} /></div><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#147a89]">Italia · 2026</p><h1 className="font-serif text-lg font-semibold sm:text-xl">El viaje de Lucas</h1></div></div>
      <div className="hidden items-center gap-3 md:flex"><span className="text-sm text-black/50">Siguiente: <strong className="text-[#14211e]">{nextAction}</strong></span><div className="h-2 w-28 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[#e4603b]" style={{ width: `${progress}%` }} /></div><span className="text-sm font-bold tabular-nums">{progress}%</span></div>
      <button onClick={savePlan} className="min-h-11 rounded-full bg-[#14211e] px-5 text-sm font-bold text-white transition hover:bg-[#147a89]">{saved ? "Guardado ✓" : "Guardar cambios"}</button>
    </div></header>

    <section className="mx-auto max-w-[1500px] px-4 pb-5 pt-4 sm:px-7 lg:px-10 lg:pt-7"><div className="relative min-h-[410px] overflow-hidden rounded-[30px] bg-[#123f47] shadow-[0_30px_80px_rgba(18,63,71,.22)] sm:min-h-[460px]">
      <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1604132588096-f00539690d1c?auto=format&fit=crop&w=2200&q=85')] bg-cover bg-center" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,29,34,.94)_0%,rgba(8,29,34,.72)_48%,rgba(8,29,34,.2)_100%)]" />
      <div className="relative flex min-h-[410px] max-w-3xl flex-col justify-between p-6 text-white sm:min-h-[460px] sm:p-10 lg:p-12"><div className="flex flex-wrap gap-2 text-sm font-semibold"><span className="rounded-full border border-white/25 bg-white/10 px-3 py-1.5 backdrop-blur">20–25 septiembre</span><span className="rounded-full border border-white/25 bg-white/10 px-3 py-1.5 backdrop-blur">Milán · Florencia · Como</span></div><div><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#f5bd58] px-3 py-1.5 text-sm font-extrabold text-[#1c302d]"><Sparkles size={15} /> Plan actualizado</div><h2 className="max-w-2xl font-serif text-4xl font-semibold leading-[1.02] sm:text-6xl">Ahora Como tiene su propia tarde.</h2><p className="mt-5 max-w-xl text-base leading-relaxed text-white/78 sm:text-lg">Llegada el jueves al mediodía, Brunate al atardecer y salida segura hacia Malpensa el viernes. Bellagio queda para otro viaje.</p><button onClick={() => { setActiveDay(4); document.getElementById("planner")?.scrollIntoView({ behavior: "smooth" }); }} className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-5 text-sm font-extrabold text-[#123f47] transition hover:-translate-y-0.5">Ver el nuevo plan de Como <ArrowRight size={17} /></button></div></div>
      <a href="https://unsplash.com/photos/0RWwg3LYfi4" target="_blank" rel="noreferrer" className="absolute bottom-4 right-5 text-xs text-white/55 hover:text-white">Foto: Unsplash</a>
    </div></section>

    <section id="planner" className="mx-auto max-w-[1500px] px-4 py-5 sm:px-7 lg:px-10 lg:py-8">
      <div className="mb-5 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-extrabold uppercase tracking-[0.17em] text-[#147a89]">Itinerario vivo</p><h2 className="mt-1 font-serif text-3xl font-semibold sm:text-4xl">Seis días, una ruta clara</h2></div><p className="max-w-xl text-sm leading-relaxed text-black/55">Pulsa un día para abrirlo. Puedes ajustar horas y marcar preparativos; los cambios se guardan en este dispositivo.</p></div>
      <div className="scrollbar-none mb-5 flex gap-2 overflow-x-auto pb-2">{days.map((day, index) => <button key={day.short} onClick={() => setActiveDay(index)} className={`group min-w-[172px] rounded-2xl border p-3 text-left transition sm:min-w-[190px] ${activeDay === index ? "border-[#123f47] bg-[#123f47] text-white shadow-lg" : "border-black/10 bg-white hover:-translate-y-0.5 hover:border-black/20"}`}><div className="flex items-center justify-between"><span className={`text-xs font-extrabold tracking-[0.14em] ${activeDay === index ? "text-white/60" : "text-black/42"}`}>{day.short}</span><span className="h-2.5 w-2.5 rounded-full" style={{ background: day.color }} /></div><strong className="mt-2 block text-base">{day.city}</strong><span className={`mt-1 block text-sm ${activeDay === index ? "text-white/62" : "text-black/48"}`}>{day.eyebrow}</span></button>)}</div>

      <Tabs defaultValue="plan" className="w-full"><TabsList className="mb-5 grid h-auto w-full grid-cols-4 rounded-2xl border border-black/10 bg-white p-1 sm:w-fit sm:min-w-[560px]"><TabsTrigger value="plan" className="min-h-11 rounded-xl">Plan</TabsTrigger><TabsTrigger value="transporte" className="min-h-11 rounded-xl">Transporte</TabsTrigger><TabsTrigger value="mapa" className="min-h-11 rounded-xl">Mapa</TabsTrigger><TabsTrigger value="comer" className="min-h-11 rounded-xl">Comer</TabsTrigger></TabsList>
        <TabsContent value="plan" className="mt-0"><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
          <section className="overflow-hidden rounded-[28px] border border-black/10 bg-white shadow-[0_18px_55px_rgba(28,48,43,.08)]"><div className="relative overflow-hidden p-6 text-white sm:p-8" style={{ background: `linear-gradient(120deg, ${active.color}, #14211e)` }}><div className="absolute -right-14 -top-20 h-56 w-56 rounded-full border-[34px] border-white/8" /><div className="relative"><div className="mb-3 flex items-center gap-2 text-sm font-bold uppercase tracking-[0.14em] text-white/65"><HeroIcon city={active.city} /> {active.date}</div><h2 className="max-w-3xl font-serif text-3xl font-semibold leading-tight sm:text-4xl">{active.title}</h2><p className="mt-3 max-w-2xl text-base leading-relaxed text-white/76">{active.summary}</p></div></div>
            <div className="divide-y divide-black/8">{active.stops.map((stop, index) => { const done = stop.booked || checked[stop.id]; return <article key={stop.id} className={`grid grid-cols-[76px_minmax(0,1fr)] gap-3 px-4 py-5 sm:grid-cols-[90px_minmax(0,1fr)_auto] sm:px-7 ${stop.important ? "bg-[#fff8ea]" : ""}`}><div><input aria-label={`Hora de ${stop.title}`} type="time" value={times[stop.id] ?? stop.time} onChange={(event) => setTimes((current) => ({ ...current, [stop.id]: event.target.value }))} className="w-[72px] rounded-xl border border-black/10 bg-[#f4f1ea] px-2 py-2.5 text-sm font-extrabold tabular-nums outline-none focus:border-[#147a89] focus:ring-2 focus:ring-[#147a89]/15 sm:w-[84px]" />{index < active.stops.length - 1 && <div className="ml-5 mt-2 h-10 w-px bg-black/12" />}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-bold leading-tight">{stop.title}</h3>{stop.booked && <span className="rounded-full bg-[#147a89]/10 px-2.5 py-1 text-xs font-extrabold uppercase tracking-wide text-[#147a89]">Reservado</span>}{stop.important && <span className="rounded-full bg-[#e4603b]/10 px-2.5 py-1 text-xs font-extrabold uppercase tracking-wide text-[#bd4424]">Clave</span>}</div><p className="mt-1.5 text-base leading-relaxed text-black/60">{stop.detail}</p><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(stop.place)}`} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1.5 text-sm font-semibold text-[#147a89] hover:underline"><MapPin size={14} /> {stop.place}</a></div><button aria-label={`${done ? "Desmarcar" : "Marcar"} ${stop.title}`} onClick={() => !stop.booked && setChecked((current) => ({ ...current, [stop.id]: !current[stop.id] }))} className={`col-start-2 mt-2 inline-flex min-h-11 items-center gap-2 justify-self-start rounded-xl border px-3 text-sm font-bold sm:col-start-auto sm:mt-0 sm:self-start ${done ? "border-[#147a89] bg-[#147a89] text-white" : "border-black/12 bg-white hover:bg-black/4"}`}><Check size={16} /> {done ? "Listo" : "Preparar"}</button></article> })}</div>
          </section>
          <aside className="space-y-5">{(activeDay === 4 || activeDay === 5) && <div className="rounded-[24px] bg-[#14211e] p-6 text-white"><div className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-[0.14em] text-[#7fd0d4]"><Sparkles size={16} /> Qué ha cambiado</div><h3 className="mt-3 font-serif text-2xl font-semibold">{activeDay === 4 ? "Como sustituye a Milán" : "Bellagio queda fuera"}</h3><p className="mt-3 text-sm leading-relaxed text-white/65">{activeDay === 4 ? "La llegada al mediodía permite conocer la ciudad, caminar junto al lago y subir a Brunate con luz. Es más coherente que hacer una escala exprés en Milán." : "Con vuelo a las 14:00 no hay margen responsable para barco rápido, paseo y regreso. El lago se disfruta el jueves; el viernes solo desayuno, paseo corto y aeropuerto."}</p></div>}
            {activeDay === 5 && <div className="rounded-[24px] border border-[#e4603b]/25 bg-[#fff1e9] p-6"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 shrink-0 text-[#c64829]" size={21} /><div><h3 className="font-bold">Hora límite: 09:00</h3><p className="mt-1 text-sm leading-relaxed text-black/62">Si a esa hora no estás en ruta, cambia al taxi. La web prioriza llegar a MXP sobre exprimir una hora más en el lago.</p></div></div></div>}
            <div className="rounded-[24px] border border-black/10 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#147a89]">Preparación</p><h3 className="mt-1 font-serif text-2xl font-semibold">{readyStops} de {totalStops} pasos</h3></div><span className="text-3xl font-extrabold text-[#e4603b]">{progress}%</span></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-black/8"><div className="h-full rounded-full bg-[#e4603b] transition-all" style={{ width: `${progress}%` }} /></div><p className="mt-3 text-sm text-black/52">Reservas confirmadas y preparativos marcados.</p></div>
            <div className="rounded-[24px] border border-black/10 bg-white p-6"><h3 className="font-serif text-2xl font-semibold">Enlaces oficiales</h3><div className="mt-4 grid gap-2">{officialLinks.map(([label, href]) => <a key={label} href={href} target="_blank" rel="noreferrer" className="flex min-h-11 items-center justify-between rounded-xl border border-black/9 px-3 text-sm font-bold hover:border-[#147a89]/40 hover:bg-[#e7f2f1]"><span>{label}</span><ExternalLink size={15} className="text-black/35" /></a>)}</div></div>
          </aside>
        </div></TabsContent>

        <TabsContent value="transporte" className="mt-0"><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_390px]">
          <section className="rounded-[28px] border border-black/10 bg-white p-5 shadow-[0_18px_55px_rgba(28,48,43,.08)] sm:p-8"><p className="text-sm font-extrabold uppercase tracking-[0.14em] text-[#147a89]">Viernes 25 · Como → MXP</p><div className="mt-2 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><h2 className="font-serif text-3xl font-semibold sm:text-4xl">Elige tu margen</h2><span className="text-sm text-black/48">Vuelo 14:00 · llegada objetivo 10:30–11:00</span></div><div className="mt-6 grid gap-3">{transfers.map((option) => { const Icon = option.icon; return <article key={option.title} className="grid gap-4 rounded-2xl border border-black/10 bg-[#faf8f3] p-5 md:grid-cols-[52px_minmax(0,1fr)_auto] md:items-center"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e7f2f1] text-[#147a89]"><Icon size={22} /></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-bold">{option.title}</h3><span className="rounded-full bg-white px-2.5 py-1 text-xs font-extrabold text-[#147a89]">{option.badge}</span></div><p className="mt-1 text-sm leading-relaxed text-black/56">{option.detail}</p><div className="mt-2 flex flex-wrap gap-4 text-sm font-bold"><span className="inline-flex items-center gap-1.5"><Clock3 size={14} /> {option.time}</span><span className="text-[#bd4424]">{option.leave}</span></div></div><a href={option.href} target="_blank" rel="noreferrer" aria-label={`Abrir información de ${option.title}`} className="grid h-11 w-11 place-items-center rounded-xl border border-black/10 bg-white hover:bg-[#e7f2f1]"><ExternalLink size={17} /></a></article> })}</div></section>
          <aside className="rounded-[28px] bg-[#123f47] p-6 text-white sm:p-7"><p className="text-sm font-extrabold uppercase tracking-[0.14em] text-[#7fd0d4]">Mi salida</p><h2 className="mt-2 font-serif text-3xl font-semibold">¿Tren o taxi?</h2><div className="mt-5 grid grid-cols-2 gap-2 rounded-2xl bg-white/8 p-1"><button onClick={() => setFlightMode("train")} className={`min-h-12 rounded-xl text-sm font-bold ${flightMode === "train" ? "bg-white text-[#123f47]" : "text-white/70"}`}>Tren</button><button onClick={() => setFlightMode("taxi")} className={`min-h-12 rounded-xl text-sm font-bold ${flightMode === "taxi" ? "bg-white text-[#123f47]" : "text-white/70"}`}>Taxi</button></div><div className="mt-5 rounded-2xl border border-white/12 bg-white/7 p-5"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#7fd0d4]">Recomendación activa</p><h3 className="mt-2 text-xl font-bold">{flightMode === "train" ? "Estar en Como Lago a las 08:30" : "Recogida en el hotel a las 08:45"}</h3><p className="mt-3 text-sm leading-relaxed text-white/65">{flightMode === "train" ? "Apunta al tren de las 08:46 o uno anterior y protege el cambio en Saronno. Confirma los minutos exactos en Trenord la víspera." : "Reserva con antelación, indica la terminal y mantén margen para tráfico. Es la opción más relajada con maletas."}</p></div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-[#f5bd58] p-4 text-[#1c302d]"><Plane size={22} /><div><strong className="block">MXP antes de las 11:00</strong><span className="text-sm">Ese es el objetivo, no la hora de salida.</span></div></div></aside>
        </div></TabsContent>

        <TabsContent value="mapa" className="mt-0"><div className="grid overflow-hidden rounded-[28px] border border-black/10 bg-white shadow-[0_18px_55px_rgba(28,48,43,.08)] lg:grid-cols-[370px_minmax(0,1fr)]"><aside className="border-b border-black/10 p-5 lg:border-b-0 lg:border-r sm:p-7"><span className="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-sm font-bold text-white" style={{ background: active.color }}><HeroIcon city={active.city} /> {active.city}</span><h2 className="mt-4 font-serif text-3xl font-semibold">{active.date}</h2><p className="mt-2 text-sm leading-relaxed text-black/55">Abre cada lugar para obtener navegación en directo. El mapa solo sirve para entender el recorrido.</p><div className="mt-5 space-y-2">{active.stops.map((stop) => <a key={stop.id} href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(stop.place)}`} target="_blank" rel="noreferrer" className="group flex min-h-14 items-center gap-3 rounded-xl border border-black/9 p-3 hover:border-[#147a89]/40 hover:bg-[#e7f2f1]"><span className="grid h-9 w-12 shrink-0 place-items-center rounded-lg bg-[#f4f1ea] text-xs font-extrabold tabular-nums">{times[stop.id] ?? stop.time}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{stop.title}</strong><span className="block truncate text-xs text-black/45">{stop.place}</span></span><ChevronRight size={16} className="text-black/30 transition group-hover:translate-x-0.5" /></a>)}</div></aside><div className="relative min-h-[580px] bg-[#dce8e3]"><iframe key={active.map} title={`Mapa de ${active.city}`} src={active.map} loading="lazy" className="absolute inset-0 h-full w-full border-0" /><div className="absolute bottom-4 left-4 right-4 rounded-2xl bg-[#14211e]/92 p-4 text-sm text-white shadow-xl backdrop-blur sm:left-auto sm:max-w-sm"><div className="flex items-center gap-2 font-bold"><MapPin size={16} /> Recorrido de {active.city}</div><p className="mt-1 text-white/60">Las ubicaciones del plan abren Google Maps en una pestaña nueva.</p></div></div></div></TabsContent>

        <TabsContent value="comer" className="mt-0"><div className="grid gap-5 xl:grid-cols-[360px_minmax(0,1fr)]"><aside className="rounded-[28px] bg-[#e4603b] p-7 text-white"><Utensils size={26} /><h2 className="mt-5 font-serif text-4xl font-semibold">Comer con sentido de ruta</h2><p className="mt-4 text-base leading-relaxed text-white/78">Pocas decisiones, bien colocadas. Reserva solo la cena que realmente te importe; deja el resto flexible.</p><div className="mt-7 rounded-2xl border border-white/20 bg-white/10 p-4 text-sm leading-relaxed"><strong className="block">Regla anti-trampa</strong><span className="text-white/72">Evita cartas interminables con fotos y captadores junto a los monumentos. Mejor carta corta, precios visibles y producto de temporada.</span></div></aside><section className="rounded-[28px] border border-black/10 bg-white p-5 shadow-[0_18px_55px_rgba(28,48,43,.08)] sm:p-8"><p className="text-sm font-extrabold uppercase tracking-[0.14em] text-[#147a89]">Selección breve</p><h2 className="mt-1 font-serif text-3xl font-semibold sm:text-4xl">Qué probar y cuándo</h2><div className="mt-6 grid gap-3 md:grid-cols-2">{food.map((item) => <article key={item.dish} className="rounded-2xl border border-black/9 bg-[#faf8f3] p-5"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-[#e7f2f1] px-2.5 py-1 text-xs font-extrabold text-[#147a89]">{item.city}</span><span className="text-xs font-bold uppercase tracking-wide text-black/38">{item.when}</span></div><h3 className="mt-4 text-xl font-bold">{item.dish}</h3><p className="mt-2 text-sm leading-relaxed text-black/55">{item.note}</p></article>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><a href="https://www.google.com/maps/search/trattoria+Oltrarno+Florence" target="_blank" rel="noreferrer" className="flex min-h-14 items-center justify-between rounded-2xl bg-[#14211e] px-4 text-sm font-bold text-white">Buscar en Oltrarno <ArrowRight size={17} /></a><a href="https://www.google.com/maps/search/ristorante+tipico+Como" target="_blank" rel="noreferrer" className="flex min-h-14 items-center justify-between rounded-2xl bg-[#147a89] px-4 text-sm font-bold text-white">Buscar cocina de Como <ArrowRight size={17} /></a></div></section></div></TabsContent>
      </Tabs>
    </section>

    <section className="mx-auto max-w-[1500px] px-4 pb-10 sm:px-7 lg:px-10"><div className="grid gap-4 rounded-[28px] border border-black/10 bg-white p-5 sm:p-7 lg:grid-cols-3"><div className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#e7f2f1] text-[#147a89]"><Backpack size={20} /></div><div><strong>La víspera</strong><p className="mt-1 text-sm leading-relaxed text-black/50">Descarga billetes, revisa terminal y deja las maletas cerradas.</p></div></div><div className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#fff1e9] text-[#bd4424]"><Ship size={20} /></div><div><strong>Sin barco el viernes</strong><p className="mt-1 text-sm leading-relaxed text-black/50">El paseo en lago se disfruta el jueves desde tierra y Brunate.</p></div></div><div className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#fff8dd] text-[#9a650b]"><FerrisWheel size={20} /></div><div><strong>Plan B sencillo</strong><p className="mt-1 text-sm leading-relaxed text-black/50">Si llueve en Como: Duomo, centro histórico y cafés bajo soportales.</p></div></div></div></section>
    <footer className="border-t border-black/8 px-4 py-6 text-center text-sm text-black/45">Plan personal · Horarios operativos: reconfirmar en las webs oficiales 24 horas antes.</footer>
  </main>;
}
